[package]
name = "rocolatey-server"
version = "0.5.5"
authors = ["Manfred Wallner <schusterfredl@mwallner.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocolatey-lib = { path = "../rocolatey-lib" }
clap = "3.1.15"
tokio = { version = "1.18.0", features = ["full"] }
warp = "0.3.2"
