[package]
name = "roco"
version = "0.5.5"
authors = ["Manfred Wallner <schusterfredl@mwallner.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocolatey-lib = { path = "../rocolatey-lib" }
tokio = { version = "1.21.2", features = ["full"] }
clap = "3.2.8"



[build-dependencies]
clap = "3.2.8"
clap_generate = "3.0.3"
clap_complete = "*"

