[package]
name = "roco"
version = "0.5.5"
authors = ["Manfred Wallner <schusterfredl@mwallner.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocolatey-lib = { path = "../rocolatey-lib" }
clap = "3.0.0-beta.4"
tokio = { version = "1.13.0", features = ["full"] }

[build-dependencies]
clap = "3.0.0-beta.4"
clap_generate = "3.0.0-beta.4"

