[package]
name = "roco"
version = "0.5.5"
authors = ["Manfred Wallner <schusterfredl@mwallner.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocolatey-lib = { path = "../rocolatey-lib" }
clap = "3.1.0"
tokio = { version = "1.17.0", features = ["full"] }

[build-dependencies]
clap = "3.1.0"
clap_generate = "3.0.3"
clap_complete = "*"

