[package]
name = "rocolatey-lib"
version = "0.5.5"
authors = ["Manfred Wallner <schusterfredl@mwallner.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.26.0"
glob = "0.3.0"
futures = "0.3.25"
reqwest = "0.11.14"
indicatif = "0.17.2"
semver = "1.0.14"
regex = "1.7.0"
walkdir = "2.3.2"
http-auth-basic = "0.3.3"
