[package]
name = "rocolatey-lib"
version = "0.5.2"
authors = ["Manfred Wallner <schusterfredl@mwallner.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.20.0"
glob = "0.3.0"
futures = "0.3.8"
reqwest = "0.10.10"
indicatif = "0.15.0"
semver = "0.11.0"
regex = "1.4.2"
walkdir = "2.3.1"
http-auth-basic = "0.1.2"
