[package]
name = "rocolatey-lib"
version = "0.5.5"
authors = ["Manfred Wallner <schusterfredl@mwallner.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.22.0"
glob = "0.3.0"
futures = "0.3.18"
reqwest = "0.11.7"
indicatif = "0.16.2"
semver = "1.0.5"
regex = "1.5.4"
walkdir = "2.3.2"
http-auth-basic = "0.3.1"
